# Generated by Django 4.2.11 on 2024-08-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_scratch_pin_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratch_pin',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
